import React, { useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import StoreLayout from '@/components/layout/StoreLayout';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from '@/components/ui/dropdown-menu';
import { Calendar, CheckCircle, Clock, CreditCard, Download, Eye, FileSpreadsheet, FileText, MapPin, Package, Search, ShoppingBag, XCircle } from 'lucide-react';
import * as XLSX from 'xlsx';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { toast } from '@/hooks/use-toast';

const mockOrders = [
  { id: 'ORD-2024-001', customer: 'João Silva', customerEmail: 'joao@empresa.com', date: '2024-03-15', status: 'completed', total: 1250.00, items: [{ id: '8006', name: 'BOMBA DE TINTA 100/200ML', quantity: 2, price: 155.00 }], paymentMethod: 'Cartão de Crédito', shippingAddress: 'Rua das Flores, 123 - São Paulo, SP' },
  { id: 'ORD-2024-002', customer: 'Maria Oliveira', customerEmail: 'maria@tecnico.com', date: '2024-03-14', status: 'processing', total: 450.90, items: [{ id: '8008', name: 'CORREIA DENTADA 150MM', quantity: 2, price: 89.90 }], paymentMethod: 'Pix', shippingAddress: 'Av. Industrial, 456 - Rio de Janeiro, RJ' },
  { id: 'ORD-2024-003', customer: 'Carlos Santos', customerEmail: 'carlos@manutencao.com', date: '2024-03-13', status: 'shipped', total: 775.00, items: [{ id: '8006', name: 'BOMBA DE TINTA 100/200ML', quantity: 5, price: 155.00 }], paymentMethod: 'Boleto', shippingAddress: 'Rua da Oficina, 789 - Belo Horizonte, MG' },
  { id: 'ORD-2024-004', customer: 'Ana Costa', customerEmail: 'ana@industria.com', date: '2024-03-12', status: 'pending', total: 320.00, items: [{ id: '8007', name: 'CABEÇA DE IMPRESSÃO TÉRMICA', quantity: 1, price: 320.00 }], paymentMethod: 'Transferência', shippingAddress: 'Zona Industrial, 321 - Salvador, BA' },
  { id: 'ORD-2024-005', customer: 'Pedro Lima', customerEmail: 'pedro@automatica.com', date: '2024-03-11', status: 'cancelled', total: 1350.00, items: [{ id: '8010', name: 'MOTOR PASO A PASO NEMA 23', quantity: 3, price: 450.00 }], paymentMethod: 'Cartão de Crédito', shippingAddress: 'Distrito Industrial, 654 - Fortaleza, CE' },
];

const money = (v:number)=>`R$ ${v.toLocaleString('pt-BR',{minimumFractionDigits:2})}`;
const getStatusText = (status: string) => ({ completed:'Concluído', processing:'Processando', shipped:'Enviado', pending:'Pendente', cancelled:'Cancelado' } as any)[status] || 'Desconhecido';
const getStatusBadge = (status: string) => { const map:any={completed:'bg-emerald-100 text-emerald-700 border-emerald-200',processing:'bg-blue-100 text-blue-700 border-blue-200',shipped:'bg-violet-100 text-violet-700 border-violet-200',pending:'bg-amber-100 text-amber-700 border-amber-200',cancelled:'bg-red-100 text-red-700 border-red-200'}; return <Badge variant="outline" className={map[status]||''}>{getStatusText(status)}</Badge>; };
const getStatusIcon = (status: string) => status==='completed'?<CheckCircle className="h-4 w-4 text-emerald-600"/>:status==='cancelled'?<XCircle className="h-4 w-4 text-red-600"/>:status==='shipped'?<Package className="h-4 w-4 text-violet-600"/>:<Clock className="h-4 w-4 text-amber-600"/>;

const CompanyOrders = () => {
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedStatus, setSelectedStatus] = useState('all');
  const [selectedOrder, setSelectedOrder] = useState<typeof mockOrders[0] | null>(null);
  const [isViewDialogOpen, setIsViewDialogOpen] = useState(false);

  const filteredOrders = useMemo(()=>mockOrders.filter(order => (order.id.toLowerCase().includes(searchTerm.toLowerCase()) || order.customer.toLowerCase().includes(searchTerm.toLowerCase()) || order.customerEmail.toLowerCase().includes(searchTerm.toLowerCase())) && (selectedStatus==='all'||order.status===selectedStatus)),[searchTerm,selectedStatus]);
  const totalRevenue = mockOrders.filter(o=>o.status==='completed').reduce((s,o)=>s+o.total,0);

  const exportToExcel = () => { const ws=XLSX.utils.json_to_sheet(filteredOrders.map(o=>({'ID do Pedido':o.id,Cliente:o.customer,Email:o.customerEmail,Data:new Date(o.date).toLocaleDateString('pt-BR'),Status:getStatusText(o.status),Total:money(o.total),Pagamento:o.paymentMethod,Endereço:o.shippingAddress}))); const wb=XLSX.utils.book_new(); XLSX.utils.book_append_sheet(wb,ws,'Pedidos'); XLSX.writeFile(wb,`pedidos_${new Date().toISOString().split('T')[0]}.xlsx`); toast({title:'Sucesso',description:'Arquivo Excel exportado.'}); };
  const exportToPDF = () => { const doc=new jsPDF(); doc.text('Relatório de Pedidos',14,22); autoTable(doc,{startY:35,head:[['ID','Cliente','Data','Status','Total','Pagamento']],body:filteredOrders.map(o=>[o.id,o.customer,new Date(o.date).toLocaleDateString('pt-BR'),getStatusText(o.status),money(o.total),o.paymentMethod]),headStyles:{fillColor:[109,40,217]}}); doc.save(`pedidos_${new Date().toISOString().split('T')[0]}.pdf`); toast({title:'Sucesso',description:'PDF exportado.'}); };

  return <StoreLayout title="Pedidos" subtitle="Acompanhe pedidos recebidos, status, pagamentos e exportações." action={<DropdownMenu><DropdownMenuTrigger asChild><Button className="bg-white text-violet-950 hover:bg-violet-100"><Download className="mr-2 h-4 w-4"/>Exportar</Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onClick={exportToExcel}><FileSpreadsheet className="mr-2 h-4 w-4 text-emerald-600"/>Excel</DropdownMenuItem><DropdownMenuItem onClick={exportToPDF}><FileText className="mr-2 h-4 w-4 text-red-600"/>PDF</DropdownMenuItem></DropdownMenuContent></DropdownMenu>}>
    <div className="space-y-6">
      <div className="grid gap-4 md:grid-cols-4">{[{label:'Total de pedidos',value:mockOrders.length},{label:'Concluídos',value:mockOrders.filter(o=>o.status==='completed').length},{label:'Pendentes',value:mockOrders.filter(o=>['pending','processing'].includes(o.status)).length},{label:'Receita total',value:money(totalRevenue)}].map(item=><Card key={item.label} className="border-slate-200 bg-white"><CardContent className="p-5"><p className="text-sm font-bold text-slate-500">{item.label}</p><p className="mt-2 text-3xl font-black text-slate-950">{item.value}</p></CardContent></Card>)}</div>
      <Card className="border-slate-200 bg-white"><CardContent className="p-5"><div className="flex flex-col gap-4 md:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><Input className="h-11 pl-10" placeholder="Buscar por ID, cliente ou email..." value={searchTerm} onChange={e=>setSearchTerm(e.target.value)}/></div><select value={selectedStatus} onChange={e=>setSelectedStatus(e.target.value)} className="h-11 rounded-md border border-slate-200 bg-white px-4 text-sm"><option value="all">Todos os status</option><option value="pending">Pendente</option><option value="processing">Processando</option><option value="shipped">Enviado</option><option value="completed">Concluído</option><option value="cancelled">Cancelado</option></select></div></CardContent></Card>
      <Card className="border-slate-200 bg-white"><CardHeader><CardTitle className="text-slate-950">Lista de pedidos</CardTitle><CardDescription>Visualize e gerencie todos os pedidos recebidos.</CardDescription></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>ID</TableHead><TableHead>Cliente</TableHead><TableHead>Data</TableHead><TableHead>Status</TableHead><TableHead>Total</TableHead><TableHead>Pagamento</TableHead><TableHead>Ações</TableHead></TableRow></TableHeader><TableBody>{filteredOrders.map(order=><TableRow key={order.id}><TableCell className="font-bold">{order.id}</TableCell><TableCell><p className="font-semibold text-slate-950">{order.customer}</p><p className="text-xs text-slate-500">{order.customerEmail}</p></TableCell><TableCell>{new Date(order.date).toLocaleDateString('pt-BR')}</TableCell><TableCell><div className="flex items-center gap-2">{getStatusIcon(order.status)}{getStatusBadge(order.status)}</div></TableCell><TableCell className="font-bold text-violet-700">{money(order.total)}</TableCell><TableCell>{order.paymentMethod}</TableCell><TableCell><Button variant="outline" size="sm" onClick={()=>{setSelectedOrder(order);setIsViewDialogOpen(true);}}><Eye className="h-4 w-4"/></Button></TableCell></TableRow>)}</TableBody></Table></CardContent></Card>
      <Dialog open={isViewDialogOpen} onOpenChange={setIsViewDialogOpen}><DialogContent className="max-w-3xl"><DialogHeader><DialogTitle>Detalhes do pedido</DialogTitle><DialogDescription>Informações completas do pedido {selectedOrder?.id}</DialogDescription></DialogHeader>{selectedOrder&&<div className="space-y-5"><div className="flex justify-between border-b pb-4"><div className="flex items-center gap-2">{getStatusIcon(selectedOrder.status)}{getStatusBadge(selectedOrder.status)}</div><div className="flex items-center gap-2 text-sm text-slate-500"><Calendar className="h-4 w-4"/>{new Date(selectedOrder.date).toLocaleDateString('pt-BR')}</div></div><Card><CardContent className="p-4"><p><b>Cliente:</b> {selectedOrder.customer}</p><p><b>Email:</b> {selectedOrder.customerEmail}</p><p className="flex gap-2"><MapPin className="mt-1 h-4 w-4"/>{selectedOrder.shippingAddress}</p></CardContent></Card><Table><TableHeader><TableRow><TableHead>Produto</TableHead><TableHead>Qtd</TableHead><TableHead className="text-right">Subtotal</TableHead></TableRow></TableHeader><TableBody>{selectedOrder.items.map((item,i)=><TableRow key={i}><TableCell>{item.name}</TableCell><TableCell>{item.quantity}</TableCell><TableCell className="text-right font-bold">{money(item.price*item.quantity)}</TableCell></TableRow>)}</TableBody></Table><div className="flex justify-between border-t pt-4"><span className="flex items-center gap-2"><CreditCard className="h-4 w-4"/>{selectedOrder.paymentMethod}</span><b className="text-xl text-violet-700">{money(selectedOrder.total)}</b></div></div>}</DialogContent></Dialog>
    </div>
  </StoreLayout>;
};
export default CompanyOrders;
