// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zvokljetwvykcpolyqgp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp2b2tsamV0d3Z5a2Nwb2x5cWdwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0ODc1MzYsImV4cCI6MjA2NzA2MzUzNn0.qd3pJLHgbnKcyMvDG7iynYR58lIcYoso0S5I7BvlTZE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});